activemq-service:
  build: ./5.15.9
  container_name: activemq
  environment:
    - TZ=CEST
  expose:
    - 8161 # Aplicacion web.
    - 61616 # Puerto de comunicacion tcp.
    - 5672 # Puerto amq.
    - 61613 # Puerto stomp.
    - 1883 # Puerto mqtt.
    - 61614 # Puerto ws.
  ports:
    - 8161:8161
    - 61616:61616
    - 5672:5672
    - 61613:61613
    - 1883:1883
    - 61614:61614
